#!/usr/bin/env bash
# Script that configures Nginx for URL redirection

sudo apt update
sudo apt -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=dQw4w9WgXcQ&t=145s&ab_channel=RickAstley;}' /etc/nginx/sites-available/default
sudo sed -i '/^}$/i \ \n\tlocation @404 {return 404 "Ceci n'\''est pas une page\\n";}' /etc/nginx/sites-available/default
sudo sed -i 's/=404/@404/g' /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
