#!/usr/bin/env bash
# Install your load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sed -i "9i ENABLED=1" /etc/default/haproxy
sudo cat >> /etc/haproxy/haproxy.cfg <<EOF

frontend yo-ti.tech
        bind *:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 369326-web-01 54.173.164.103:80 check
        server 369326-web-02 34.224.83.198:80 check

EOF 

service haproxy restart
